FROM python:3.12-slim

WORKDIR /app

COPY inference_service /app/inference_service
COPY src /app/src
COPY data/raw /app/data/raw
COPY requirements.txt /app

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8002

ENV NAME InferenceService

CMD ["uvicorn", "inference_service.main:app", "--host", "0.0.0.0", "--port", "8002"]
