FROM python:3.12-slim

WORKDIR /app

COPY preprocessing_service /app/preprocessing_service
COPY src /app/src
COPY data/raw/customer_purchases.csv /app/data/raw/
COPY requirements.txt /app

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8001

ENV NAME PreprocessingService

CMD ["uvicorn", "preprocessing_service.main:app", "--host", "0.0.0.0", "--port", "8001"]
