FROM python:3.12-slim

WORKDIR /app

COPY model_registry /app/model_registry
COPY models /app/models
COPY requirements.txt /app

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

ENV NAME ModelRegistry

CMD ["uvicorn", "model_registry.api:app", "--host", "0.0.0.0", "--port", "8000"]
